Init
keboola/db-writer-config pull request #1
Opened 2023-10-18 22:07 UTC by ondrajodas

2024-02-08 09:59 UTC, AdamVyborny commented
@ondrajodas za mě to vypadá dobře. Jenom několik pointů:
1. README
2. Branch protection na repu
3. Nejsem si jistý toho readonly na těch value objektech. Neznamená to, že pak nepůjdou extendnout, například ve SNFK writeru, kdy tam budu chtít přihodit warehouse etc. nebo něco podobného, kde bude potřeba nějaký údaj navíc?

2024-02-08 10:03 UTC, ondrajodas commented
1./2. - good point - fixing
3. - ne to znamená že všechny property jsou readonly viz jak zmiňuješ snflk - https://github.com/keboola/db-writer-snowflake/blob/CM-807-ondra/src/Configuration/ValueObject/SnowflakeDatabaseConfig.php

2024-02-08 10:07 UTC, AdamVyborny commented
jo, sorry já si to blbě přečetl. Nemůžeš extendovat non-readonly classou, né že by to nešlo vůbec. 👍

2024-02-08 10:09 UTC, ondrajodas commented
jo non-readonly classou to nejde

2024-02-08 21:22 UTC, ondrajodas commented
@AdamVyborny je to fixnutý

2024-02-09 12:31 UTC, AdamVyborny requested changes

2024-02-09 12:31 UTC, AdamVyborny commented on README.md
> +```yml
Tohle má být `bash` a klidně bych ho přidal i do těch ostatní code snippetů níž

2024-02-09 12:35 UTC, ondrajodas commented on README.md
> +```yml
jako jooo no :)

2024-02-09 12:36 UTC, AdamVyborny approved these changes
LGTM 👍

2024-02-09 20:11 UTC, merged